#!/bin/bash
set -e

# psst! run me with `npm run dev`

if [ $npm_config_alt_config ]; then
  config=$npm_config_alt_config
else
  config=dev
fi
echo Using config $config

export NODE_ENV=development
export CONFIG_NAME=$config

npm run build
concurrently -k \
  "docker-compose -f docker-compose.dev.yml up" \
  "tsc -p server -w" \
  "nodemon -d 1 -w build build/server/localserver.js" \
  "webpack-dev-server"